title: âœ… Daniel Danielecki
description1: ğŸ† Top Stack Overflow
description2: FullStack Web & Mobile JavaScript Developer
duolingo: danieldanielecki
github: danieldanielecki
linkedin: danieldanielecki
kickstarter: danieldanielecki
metamask: 0xa6930Ea459f6391A6a50248ff69B49B2d7A27283
paypal: danieldanielecki
stackoverflow: 11127383/daniel-danielecki
stocktwits: danieldanielecki
strava: 87158328
udemy: daniel-danielecki
telegram: danieldanielecki
twitter: ddanielecki

exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
